### 로그인
POST localhost:8001/login
Content-Type: application/json

{
  "loginId" : "qaqa",
  "pwd" : "qaqa"
}

### 모임 목록 확인
GET localhost:8080/group/list

### 테스트 로그인
POST localhost:8080/login
Content-Type: application/json

{
  "loginId" : "test02",
  "pwd" : "pass02"
}